# Generated by Django 4.2.4 on 2023-11-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='advert_manager.advert'),
        ),
    ]
